docker run \
    -v "/home/$USER/scans:/scans" \
    -v "$PWD/script:/opt/brother/scanner/brscan-skey/script/" \
    -e NAME="Scanner" \
    -e MODEL="MFC-L2700DW" \
    -e IPADDRESS="10.26.9.239" \
    --env FTP_USER="${FTP_USER}" \
    --env FTP_PASSWORD="${FTP_PASSWORD}" \
    --env FTP_HOST="${FTP_HOST}" \
    --env FTP_PATH="${FTP_PATH}" \
    --net=host brother-scanner
